### ISSUE TITLE
How-to compile and work with pysimulavr

### ISSUE THREAD

**Issue by Valber** [Traumflug/simulavr#12]
System Ubuntu 15.04 , swig 2.0.12-1ubuntu1 - installed

```
git clone https://github.com/Traumflug/simulavr.git
./bootstrap
./configure LDFLAGS="-L/usr/lib/python2.7" --enable-python
make
sudo checkinstall
cd src/python 
sudo python setup.py install

python -c 'import pysimulavr'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pysimulavr-1.1.dev0-py2.7-linux-x86_64.egg/pysimulavr.py", line 28, in <module>
    _pysimulavr = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pysimulavr-1.1.dev0-py2.7-linux-x86_64.egg/pysimulavr.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pysimulavr', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/pysimulavr-1.1.dev0-py2.7-linux-x86_64.egg/_pysimulavr.so: undefined symbol: _ZTI14RWMemoryMember
```

What's wrong?

**Comment by Traumflug** [comment]
Sorry, can't say much about this, so far I never used the Python interface. I run SimulAVR always from the command line directly. Maybe you have more luck on the [SimulAVR mailing list](https://lists.nongnu.org/mailman/listinfo/simulavr-devel), because what you see here adds the SIMINFO mechanism only, everything else is identical to [upstream](http://www.nongnu.org/simulavr/).
